# Generated by Django 3.1.3 on 2020-11-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glamping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de identificacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateField(null=True, unique=True, verbose_name='Fecha de entrada')),
                ('date_departure', models.DateField(null=True, unique=True, verbose_name='Fecha de salida')),
                ('phone', models.CharField(max_length=45, null=True, unique=True, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Correo electronico')),
                ('glamping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glamping.glamping', verbose_name='Glamping')),
            ],
            options={
                'verbose_name': 'Gampling',
                'ordering': ['id'],
            },
        ),
    ]
