# Generated by Django 3.1.3 on 2020-11-13 03:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Glamping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción')),
                ('quantity_person', models.PositiveIntegerField(null=True, verbose_name='Cantidad de persona')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Imagen')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glamping.status', verbose_name='Estado')),
            ],
            options={
                'verbose_name': ('Glamping',),
                'verbose_name_plural': 'Glamping',
                'ordering': ['id'],
            },
        ),
    ]
